import "dotenv/config";
import { getGitSummary } from "./git.js";
import { getWeatherSummary } from "./weather.js";
import { getNews } from "./news/index.js";
import { translateNewsTitles } from "./news/translate-news.js";
import { summarizeWithOllama } from "./ollama.js";
import { buildDailyBriefingPrompt } from "./prompt.js";
import { sendBriefing } from "./mail.js";

async function main() {
    const repoPath = process.argv[2];
    const model = process.argv[3] ?? "qwen3.5:9b";

    if (!repoPath) {
        throw new Error("Usage: npx tsx src/index.ts <repository-path> [model]");
    }

    console.log(`Collecting Git activity from: ${repoPath}`);
    console.log(`Model: ${model}`);

    const [gitSummary, weatherSummary, rawNewsSummary] = await Promise.all([
        safeCollect("Git activity", () => getGitSummary(repoPath, "7 days ago")),
        safeCollect("weather", () => getWeatherSummary()),
        safeCollect("news", () => getNews()),
    ]);

    let newsSummary = rawNewsSummary;

    if (rawNewsSummary) {
        const translatedGeneralNews = await safeCollect("news title translation", () => translateNewsTitles(rawNewsSummary.general, model));

        if (translatedGeneralNews) {
            newsSummary = {
                ...rawNewsSummary,
                general: translatedGeneralNews,
            };
        }
    }

    console.log("\n=== Structured Git Data ===\n");
    console.log(JSON.stringify(gitSummary, null, 2));

    console.log("\n=== Structured Weather Data ===\n");
    console.log(JSON.stringify(weatherSummary, null, 2));

    console.log("\n=== Structured News Data ===\n");
    console.log(JSON.stringify(newsSummary, null, 2));

    const prompt = buildDailyBriefingPrompt(gitSummary, weatherSummary, newsSummary);

    console.log("\n=== AI Daily Briefing ===\n");

    const generatedBriefing = await summarizeWithOllama(model, prompt, (token) => process.stdout.write(token));

    const footer = `This briefing has been AI-generated by **${model}**.`;

    const briefing = `${generatedBriefing.trim()}\n\n---\n\n${footer}`;

    console.log(`\n\n---\n\n${footer}`);

    await sendBriefing(briefing);
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});

async function safeCollect<T>(label: string, collector: () => Promise<T>): Promise<T | null> {
    try {
        return await collector();
    } catch (error) {
        console.error(`Failed to collect ${label}:`, error);
        return null;
    }
}
